return {
  -- {
  --   'zbirenbaum/copilot.lua',
  --   event = 'InsertEnter',
  --   enabled = not vim.g.vscode,
  --   cmd = 'Copilot',
  --   config = function()
  --     require('copilot').setup {
  --       suggestion = { enabled = false },
  --       panel = { enabled = false },
  --     }
  --   end,
  -- },
  -- {
  --   'yetone/avante.nvim',
  --   event = 'VeryLazy',
  --   build = 'make',
  --   opts = {
  --     provider = 'copilot',
  --     hints = {
  --       enabled = false,
  --     },
  --   },
  --   dependencies = {
  --     'nvim-treesitter/nvim-treesitter',
  --     'stevearc/dressing.nvim',
  --     'nvim-lua/plenary.nvim',
  --     'MunifTanjim/nui.nvim',
  --     --- The below dependencies are optional,
  --     -- 'echasnovski/mini.pick',
  --     'nvim-telescope/telescope.nvim',
  --     'hrsh7th/nvim-cmp',
  --     -- 'ibhagwan/fzf-lua',
  --     'nvim-tree/nvim-web-devicons',
  --     'zbirenbaum/copilot.lua',
  --     -- 'MeanderingProgrammer/render-markdown.nvim',
  --     -- {
  --     --   'HakonHarnes/img-clip.nvim',
  --     --   event = 'VeryLazy',
  --     --   opts = {
  --     --     default = {
  --     --       embed_image_as_base64 = false,
  --     --       prompt_for_file_name = false,
  --     --       drag_and_drop = {
  --     --         insert_mode = true,
  --     --       },
  --     --       use_absolute_path = true,
  --     --     },
  --     --   },
  --     -- },
  --   },
  -- },
}
